#A framework for building
NewResult({'A framework for building': {u'Abstract': u'',
                              u'AbstractSource': u'',
                              u'AbstractText': u'',
                              u'AbstractURL': u'',
                              u'Answer': u'',
                              u'AnswerType': u'',
                              u'Definition': u'',
                              u'DefinitionSource': u'',
                              u'DefinitionURL': u'',
                              u'Entity': u'',
                              u'Heading': u'',
                              u'Image': u'',
                              u'ImageHeight': u'',
                              u'ImageIsLogo': u'',
                              u'ImageWidth': u'',
                              u'Infobox': u'',
                              u'Redirect': u'',
                              u'RelatedTopics': [],
                              u'Results': [],
                              u'Type': u'',
                              u'meta': {u'attribution': None,
                                        u'blockgroup': None,
                                        u'created_date': u'2015-11-08',
                                        u'description': u'testing pr template posted to comment',
                                        u'designer': None,
                                        u'dev_date': None,
                                        u'dev_milestone': u'testing',
                                        u'developer': [{u'name': u'jdorweiler',
                                                        u'type': u'github',
                                                        u'url': u'https://github.com/jdorweiler'}],
                                        u'example_query': u'example query 1',
                                        u'id': u'template_comments',
                                        u'is_stackexchange': None,
                                        u'js_callback_name': u'jargon',
                                        u'live_date': None,
                                        u'name': u'Template_comments',
                                        u'perl_module': u'DDG::Fathead::Jargon',
                                        u'producer': u'Jag',
                                        u'repo': u'fathead',
                                        u'signal_from': u'template_comments',
                                        u'src_domain': None,
                                        u'src_id': None,
                                        u'src_name': None,
                                        u'src_options': {},
                                        u'src_url': u' ',
                                        u'status': None,
                                        u'tab': u'About',
                                        u'topic': []}}})
