* Open Source Hardware

-  Open-source hardware (OSH) consists of physical artifacts of
   technology designed and offered by the open design movement. Both
   free and open-source software (FOSS) as well as open-source hardware
   is created by this open-source culture movement and applies a like
   concept to a variety of components. It is sometimes, thus, referred
   to as FOSH (free and open source hardware). The term usually means
   that information about the hardware is easily discerned so that
   others can make it - coupling it closely to the maker movement.[1]
   Hardware design (i.e. mechanical drawings, schematics, bills of
   material, PCB layout data, HDL source code and integrated circuit
   layout data), in addition to the software that drives the hardware,
   are all released under free/libre terms. The original sharer gains
   feedback and potentially improvements on the design from the FOSH
   community. There is now significant evidence that such sharing
   creates enormous economic value.[2]

Source: [[http://en.wikipedia.org/wiki/Open-source_hardware]]

Stallman's view on free hardware:
https://www.gnu.org/philosophy/free-hardware-designs.html
