Open Educational Resources

* Twitter: 
https://twitter.com/hashtag/OER

** Recent tweets:
http://education.okfn.org/open-data-as-open-educational-resources-case-studies-of-emerging-practice/
http://www.edutopia.org/open-educational-resources-guide?utm_source=twitter&utm_medium=socialflow
http://www.hewlett.org/blog/posts/sharing-benefits-open-educational-resources-everyone
http://www.oecd-ilibrary.org/education/open-educational-resources_9789264247543-en


* MOOC
** http://chronicle.com/article/The-Brave-New-World-of-College/138107/ [[mooc]]

* K12
** http://courses.doceocenter.org/intro_to_open_education_in_k-12 and
http://courses.doceocenter.org/open_textbook_crash_course contain similar
content.

** Kimmons, R. (2014). Introduction to open education in K-12. University of Idaho
Doceo Center Open Courses. Retrieved from
http://courses.doceocenter.org/intro_to_open_education_in_k-12. Licensed under
CC BY-NC 3.0.

** Open Textbooks & Curricula
   CK-12 - http://www.ck12.org requires registration. Creative commons
   Attribution ND. 

**** Saylor - http://saylor.org 
     License : Creative Commons Attribution 3.0 Unported License. 
     Access : Open access with optional log in. 

**** Boundless - http://boundless.com 
     License : CC BY-SA 4.0 with attribution required. 
     Access : No registration required.

**** Connexions
    Connexions / OpenStax Library - http://cnx.org 
    License : Creative Commons Attribution 4.0 License. 
    Languages: Many languages. 
***** Cnn Coverage of connections :http://edition.cnn.com/2007/TECH/11/08/connexions.learning/

**** Textbook Equity - http://textbookequity.org/  Free  college level textbooks
    with Creative Commons Licenses.  Royalty-free.  Low-Cost Print. Broken
    links. 

**** BC Campus - http://open.bccampus.ca   Creative Commons
 Attribution 4.0 International License. Textbooks. 

****    Wiki Books - http://en.wikibooks.org

****    Odell Education - http://odelleducation.com/  Creative Commons
    Attribution-NonCommercial-ShareAlike 4.0 International License. Small amount.

****    Cool4Ed - http://www.cool4ed.org/ Directory of open content from california.

****    Merlot - http://www.merlot.org/merlot/index.htm MERLOT is a curated
    collection of free and open online teaching, learning, and faculty
    development services contributed and used by an international education
    community. 





** Search Engines

**    OER Commons - https://www.oercommons.org/  

*** ISKME
    http://www.iskme.org/ ISKME is an independent, education nonprofit whose
    mission is to improve the practice of continuous learning, collaboration,
    and change in the education
    sector. https://en.wikipedia.org/wiki/Institute_for_the_Study_of_Knowledge_Management_in_Education

***  Big Idea Fest  : http://www.bigideasfest.org/         

**    Creative Commons Search - http://search.creativecommons.org
**    Google Advanced Search - https://www.google.com/advanced_search  "free to use share or modify".
**    Google Advanced Image Search - http://www.google.com/advanced_image_search  "free to use share or modify".
**    Yahoo Image Search - http://images.search.yahoo.com  “Labeled for Reuse”


** Text Content Providers
***    Wikipedia - http://en.wikipedia.org - open encyclopedia
***    Simple English Wikipedia - http://simple.wikipedia.org  - simplified encyclopedia
***    Project Gutenberg - http://www.gutenberg.org - public domain texts
***    Wiki Source - http://en.wikisource.org - source materials
***    Wiki Quote - http://en.wikiquote.org - quotations

** Media Content Providers

**    Wikimedia Commons - http://commons.wikimedia.org - open media
**    Digital Public Library of America - http://dp.la/ - public domain works
**    LibriVox - http://librivox.org - public domain audio books
**    Photo Pin - http://photopin.com - open photos from Flickr
**    Internet Archive - https://archive.org - public domain works
**    U.S. Army - http://www.army.mil/media/ - public domain images
**    Flickr - http://www.flickr.com/creativecommons/ - creative commons images
**    Vimeo - http://vimeo.com/creativecommons - creative commons videos
**    Creative Commons Music - https://creativecommons.org/legalmusicforvideos - various creative commons music sites
**    Jamendo - http://jamendo.com - creative commons music
**    Animal Photos - http://animalphotos.info - animal photos
**    Library of Congress - http://www.loc.gov/ - public domain works
**    Internet Archive  - https://archive.org - public domain works
**    U.S. Fish and Wildlife Digital Library - http://digitalmedia.fws.gov/ - public domain works (mostly)
** Youtube
*** https://www.youtube.com/watch?v=ZFeyCc6we-s OER (Open Educational Resources) Introduction

** Open Courses
***   Lumen Learning - http://www.lumenlearning.com  https://courses.candelalearning.com/catalog/lumen
***   Wikiversity - http://en.wikiversity.org


* about OER
** http://er.educause.edu/articles/2005/1/open-educational-resources-serve-the-world 2005
   many of these links are dead or the projects stopped.

*** http://www.col.org/ Commonwealth of Learning (COL) is the only IGO dedicated to promoting and developing open,distance and tech enabled learning
**** publications http://oasis.col.org/

*** http://www.ibiblio.org/about/ largest “collections of collections” on the Internet

*** Utah state open courseware http://ocw.usu.edu/
**** Japan OCW http://jocw.jp/jp/
**** john hopkins http://ocw.jhsph.edu/ © 2011 The Johns Hopkins University. Creative Commons BY-NC-SA.
**** MIT http://ocw.mit.edu/index.htm
**** TUFTS http://ocw.tufts.edu/
**** http://mit.ocw.universia.net/ spanish 
**** http://www.oeconsortium.org/ The Open Education Consortium, with search engine.

*** virtual universities 
**** unsesco http://www.unesco.org/iiep/virtualuniversity/linksliste.php


** http://er.educause.edu/articles/2014/10/practicing-collaborative-digital-pedagogy-to-foster-digital-literacies-in-humanities-classrooms
   2014
   Creative Commons Attribution-NonCommercial-NoDerivs 4.0 license.

*** Ease.ly infographics
    http://www.easel.ly/

*** http://www.criticalcommons.org/ Critical Commons is an online repository of
user-generated media. The archive is a project of the Media Arts and Practice
division of the USC School of Cinematic Arts. The project supports the fair use
of copyrighted media by educators.

*** How Teens Do Research in the Digital World http://www.pewinternet.org/files/old-media/Files/Reports/2012/PIP_TeacherSurveyReportWithMethodology110112.pdf
*** Digital Literacies  A Research Briefing by the Technology Enhanced Learning phase of the Teaching and Learning Research Programme http://www.tlrp.org/docs/DigitalLiteracies.pdf
*** http://www.digitalhumanities.org/dhq/vol/3/4/000077/000077.html The Digital Future is Now: A Call to Action for the Humanities
*** The Impact of Digital Tools on Student Writing and How Writing is Taught in Schools http://www.pewinternet.org/2013/07/16/the-impact-of-digital-tools-on-student-writing-and-how-writing-is-taught-in-schools/
*** Confronting the Myth of the 'Digital Native' http://chronicle.com/article/Confronting-the-Myth-of-the/145949/ 2014


*** Googled the end of the world as we know it.
https://en.wikipedia.org/wiki/Googled:_The_End_of_the_World_as_We_Know_It
    
    Beta version : http://beta.voyant-tools.org/

*** Scalar 
   Born-digital, open source, media-rich scholarly publishing that’s as easy as
   blogging. 
   Code : https://github.com/anvc/scalar
   Language: PHP

*** Hypothesis   
    Code: https://github.com/hypothesis/h
    Language: python
    IRC: #hypothes.is on freenode for discussion.
 


* http://ijedict.dec.uwi.edu/viewarticle.php?id=878&layout=html Educators and the Cape Town Open Learning Declaration: Rhetorically reducing distance

http://msd-ord.com/index.htm/
http://oer.avu.org/
http://oerwiki.iiep.unesco.org/index.php/FOSS_solutions_for_OER_-_summary_report
http://oerworkshop.weebly.com/index.html
http://quod.lib.umich.edu/j/jii/4750978.0002.203?view=text;rgn=main
http://web.archive.org/web/19990429221830/www.opencontent.org/home.shtml
http://web.archive.org/web/20000619122406/http://www.time.com/time/digital/daily/0,2822,621,00.html
http://web.archive.org/web/20030920155754/http://www.globetechnology.com/servlet/story/RTGAM.20030904.gttwtico04/BNStory/einsider/
http://wikieducator.org/Educators_care/Defining_OER
http://wikieducator.org/Learning4Content
http://wikieducator.org/MU
http://wikieducator.org/Oer
http://writingcommons.org/about
http://www.bizjournals.com/sanjose/print-edition/2014/03/28/the-reinvention-of-neeru-khosla.html?ana=sm_sjo_ucp27&b=1395941537^14150321
http://www.capetowndeclaration.org/read-the-declaration
http://www.ceibal.edu.uy/#institucionalindex.php?option=com_content&view=article&id=486:licitacion-publica-internacional-no-01522011-seleccion-de-proveedor-para-la-adquisicion-de-plataforma-educativa-on-line-yo-recursos-educativos-digitales-para-educacion-primaria-y-media-uruguaya&catid=51:convocatorias-vigentes&Itemid=82
http://www.clrn.org/home/
http://www.clrn.org/home/
http://www.col.org/progServ/report/clippings/Pages/2006wikiEd.aspx
http://www.col.org/resources/crsMaterials/Pages/OCW-OER.aspx
http://www.collegeopentextbooks.org/blog/advocating/saylor-foundation-to-launch-multi-million-dollar-open-textbook-challenge/
http://www.educause.edu/library/open-educational-resources-oer
http://www.edutopia.org/open-educational-resources-guide
http://www.gg.rhul.ac.uk/ict4d/workingpapers/mulderOER.pdf
http://www.hewlett.org/programs/education/open-educational-resources
http://www.hewlett.org/uploads/files/Hewlett_OER_report.pdf
http://www.icde.org/UNESCO+and+COL+promote+wider+use+of+OERs.b7C_wlrQXZ.ips
http://www.icde.org/UNESCO+and+COL+promote+wider+use+of+OERs.b7C_wlrQXZ.ips
http://www.irrodl.org/index.php/irrodl/article/view/1964/3133
http://www.nytimes.com/2010/04/18/education/edlife/18open-t.html?_r=1&pagewanted=all
http://www.nytimes.com/2010/11/01/world/europe/01iht-educLede01.html?pagewanted=all
http://www.oecd.org/document/53/0,3746,en_2649_35845581_35735605_1_1_1_1,00.html
http://www.oecd.org/edu/ceri/38654317.pdf
http://www.oerafrica.org/LinkClick.aspx?fileticket=ej5-VzBXrzA%3d&tabid=113
http://www.pedocs.de/frontdoor.php?source_opus=9101
http://www.priyo.com/tech/2011/02/28/pm-opens-e-content-repository-20905.html
http://www.richmond.com/news/state-regional/community-college-to-offer-textbook-free-degree/article_d45bcffc-bea5-5049-acd3-b025170041f2.html
http://www.sourceoecd.org/education/9789264031746
http://www.surf.nl/en/publicaties/Documents/Trend%20Report%20OER%202013_EN_DEF%2007032013%20(LR).pdf
http://www.theguardian.com/education/2009/nov/10/web-technology-degree-future-online
http://www.unesco.org/fileadmin/MULTIMEDIA/HQ/ED/ED/pdf/WCHE_2009/FINAL%20COMMUNIQUE%20WCHE%202009.pdf
http://www.unesco.org/new/fileadmin/MULTIMEDIA/HQ/CI/CI/pdf/Events/Paris%20OER%20Declaration_01.pdf
http://www.webarchive.org.uk/wayback/archive/20140614005411/http://www.jisc.ac.uk/whatwedo/programmes/elearning/oer2
https://cultivatingchange.wp.d.umn.edu/community/about/
https://cultivatingchange.wp.d.umn.edu/community/ccmooc-experimenting-with-moocs-at-gpacw/
https://eliademy.com/blog/2015/03/16/oer/
https://en.wikipedia.org/wiki/Open_educational_resources
https://en.wikipedia.org/wiki/Wikiversity
https://en.wikiversity.org/wiki/Open_educational_resources
https://openpolicynetwork.org/
https://wiki.creativecommons.org/wiki/OER_Policy_Registry
https://wiki.creativecommons.org/wiki/What_is_OER%3F
https://www.academia.edu/11056576/Trends_in_Distance_Education_Research_A_Content_Analysis_of_Journals_2009-2013
https://www.evernote.com/shard/s59/sh/4f75978a-415f-4786-9132-3df5efdae7f0/a0ac2190fb9fd581c26b9fd9150f95a4
https://www.insidehighered.com/news/2013/04/08/coursera-begins-make-money
https://www.jisc.ac.uk/rd/projects/open-education
https://www.jisc.ac.uk/rd/projects/open-education
https://www.koreatimes.co.kr/www/news/nation/2011/07/117_89881.html
https://www.oecd.org/edu/ceri/36224377.pdf
https://www.oercommons.org/
https://www.shuttleworthfoundation.org/
https://www.timeshighereducation.com/features/get-it-out-in-the-open/408300.article?storycode=408300

- [[http://www.inderscience.com/offer.php?id=20233][Inderscience Publishers - linking academia, business and industry through research]]
- [[http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.669.5055&rank=5][CiteSeerX — Open educational resources: staff attitudes and awareness]]
- [[http://wiki.cetis.ac.uk/images/6/6d/OER_Briefing_Paper_CETIS_without_recommendations_with_cover_page_.pdf][OER_Briefing_Paper_CETIS_without_recommendations_with_cover_page_.pdf]]
- [[http://oro.open.ac.uk/17011/1/918Wilsonand_McAndrewCAPITAL_paperfrom_INTED_CD.pdf][918Wilsonand_McAndrewCAPITAL_paperfrom_INTED_CD.pdf]]
- [[http://kn.open.ac.uk/public/getfile.cfm?documentfileid=13440][getfile.cfm]]
- [[http://people.kmi.open.ac.uk/ale/journals/05ijl2008.pdf][Page not found | Ale Okada]]
- [[http://ceur-ws.org/Vol-1181/pale2014_paper_07.pdf][pale2014_paper_07.pdf]]

- [[http://www-jime.open.ac.uk/articles/10.5334/2013-04/][An OER COUP: College Teacher and Student Perceptions of Open Educational
  Resources]] online not pdf

- [[http://robinwofford.wiki.westga.edu/file/view/EJ837471.pdf/238606187/EJ837471.pdf][EJ837471.pdf]]
- [[http://oro.open.ac.uk/12121/1/Godwin_et_al.pdf][Godwin_et_al.pdf]]
- [[http://unex.uci.edu/pdfs/dean/matkin_apru_paper.pdf][matkin_apru_paper.pdf]]
- [[http://oro.open.ac.uk/33457/4/ferguson_chapter_okada_book.pdf][ferguson_chapter_okada_book.pdf]]
- [[https://aisantos.files.wordpress.com/2007/11/open-educational-resources-final-licensed.pdf][open-educational-resources-final-licensed.pdf]]
- [[http://reganmian.net/top-level-courses/Top-Level-Courses-2col.pdf][Top-Level-Courses-2col.pdf]]
- [[http://www.meaningprocessing.com/personalPages/tuomi/articles/OpenEducationalResourcesAndTheTransformationOfEducation.pdf][OpenEducationalResourcesAndTheTransformationOfEducation.pdf]]
- [[http://iite.unesco.org/pics/publications/en/files/3214700.pdf][3214700.pdf]]
- [[http://iite.unesco.org/pics/publications/en/files/3214680.pdf][3214680.pdf]]
- [[http://publications.cetis.org.uk/wp-content/uploads/2013/04/OER13_resourcediscovery.pdf][OER13_resourcediscovery.pdf]]
- [[http://publications.cetis.org.uk/wp-content/uploads/2012/12/into_the_wild_print.pdf][into_the_wild_print.pdf]]
- [[http://www.unde.ro/zoran/papers/X02-SOMOCO-2013-CRP2W.pdf][X02-SOMOCO-2013-CRP2W.pdf]]
- [[http://www.unde.ro/zoran/papers/X03-ICCCI-coledu2013-CRP2W.pdf][X03-ICCCI-coledu2013-CRP2W.pdf]]
- [[http://www.ulb.ac.be/unica/docs/Sch-com-2008-Schaffert.pdf][Lern- und Wissensprozesse mit Neuen Technologien. ePortfolio al - Sch-com-2008-Schaffert.pdf]]
- [[http://wiki.oercommons.org/mediawiki/upload/OER_CASE_STUDY_2_CURRIKI.pdf][Microsoft Word - OER_CASE_STUDY_2_CURRIKI.doc - OER_CASE_STUDY_2_CURRIKI.pdf]]
- [[http://www.oecd.org/dataoecd/15/1/40573667.pdf][Page not found - OECD]]
- [[http://jime.open.ac.uk/2008/07/jime-2008-07.pdf][Journal of Interactive Media in Education]]
- [[http://jime.open.ac.uk/2008/09/jime-2008-09.pdf][Journal of Interactive Media in Education]]
- [[http://oro.open.ac.uk/11810/1/IJLjournal.pdf][IJLjournal.pdf]]
- [[http://oro.open.ac.uk/23351/1/OpenEd2010-SocialLearn.pdf][OpenEd2010-SocialLearn.pdf]]
- [[http://iite.unesco.org/pics/publications/en/files/3214695.pdf][untitled - 3214695.pdf]]
- [[https://www.e-education.psu.edu/files/sites/file/GISTinOER_DiBiase.pdf][Microsoft Word - GISTinOER_DiBiase.docx - GISTinOER_DiBiase.pdf]]
- [[http://eprints.usq.edu.au/22388/1/DEQuarterly_Spring_2012_Edition_No_12.pdf][DEQuarterly_Spring_2012_Edition_No_12.pdf]]
- [[http://eprints.usq.edu.au/20455/6/Bull_Bossu_Brown_PV.pdf][Bull_Bossu_Brown_PV.pdf]]
- [[http://ceur-ws.org/Vol-311/paper12.pdf][C:\Users\Frans\AppData\Local\CutePDF_Pro\CPA69E.PDF - paper12.pdf]]
- [[http://www.tesl-ej.org/pdf/ej44/a8.pdf][TESL-EJ 11.4 -- Open Educational Resources and Practices - a8.pdf]]
- [[http://www.immagic.com/eLibrary/ARCHIVES/GENERAL/OECD_FR/O070522H.pdf][Giving Knowledge for Free: The Emergence of Open Educational Resources - O070522H.pdf]]
- [[http://oro.open.ac.uk/17831/1/EADTU_Utah_paper-_final.pdf][EADTU_Utah_paper-_final.pdf]]
- [[http://oro.open.ac.uk/29201/1/OPEN_EDUCATIONAL_RESOURCES_AND_WIDENING_PARTICIPATION_andy.pdf][OPEN_EDUCATIONAL_RESOURCES_AND_WIDENING_PARTICIPATION_andy.pdf]]
- [[http://oro.open.ac.uk/21123/1/Kozinska_et_al.pdf][Kozinska_et_al.pdf]]
- [[http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.372.3300&rep=rep1&type=pdf][download]]
- [[http://oro.open.ac.uk/17018/1/Extract_22-From_Africa_through_Germany_to_the_UK-low-res.pdf][Extract_22-From_Africa_through_Germany_to_the_UK-low-res.pdf]]
- [[http://oro.open.ac.uk/17012/1/913Wilson_and_McAndrew_POCKET_paperfrom_INTED_CD.pdf][913Wilson_and_McAndrew_POCKET_paperfrom_INTED_CD.pdf]]

**  http://oro.open.ac.uk/27022/1/OER_for_Virtual_Learning-_What_works_and_what_doesn%27t%5B1%5D.pdf
   GUIDEabstract2AIS - OER_for_Virtual_Learning-_What_works_and_what_doesn't1].pdf
- [[http://oro.open.ac.uk/17015/1/Wilson_434-442.pdf][Wilson_434-442.pdf]]
- [[http://oro.open.ac.uk/18765/2/BC228F30.pdf][BC228F30.pdf]]



Nonfree Tools used:

Googlebooks ngrams:
https://books.google.com/ngrams

Text tools :
http://voyant-tools.org/
https://www.diigo.com/

Timeline :
http://www.timetoast.com/
http://www.tiki-toki.com/

https://beta.worldcat.org/archivegrid/



To review :
http://libguides.georgefox.edu/content.php?pid=353868&sid=2926270 Open
Educational Resources

http://www.edutopia.org/open-educational-resources-guide



* Lanyard OER :
http://lanyrd.com/search/?q=OER&type=coverage

** Conferences 
*** http://www.oer13.org/
*** OER Schools Conference
    http://education.okfn.org/oer-schools-conference/
    http://www.digilitleic.com/?p=652

    http://lccdigilit.our.dmu.ac.uk/2015/02/12/oer-schools/
    https://drbadgr.wordpress.com/2015/03/05/teaching-children-about-creative-commons-licenses-to-re-use-images-oersch15/

    https://remoteworker.wordpress.com/2015/02/10/teachers-children-and-technology/


*** Oer 2015 
    http://www.mearso.co.uk/sketchnotes/oer15/

**** Keynote http://www.josiefraser.com/2015/04/oer15/ OER on Main Street
**** Writeup https://lornamcampbell.wordpress.com/2015/04/22/oer15-better-late-than-never/
**** The voice of OER15 https://www.youtube.com/watch?v=YgKuRtDRbyE
**** OER keynote https://www.youtube.com/watch?v=sDeEZ_z8XBo
**** Slides Open Education: The Business & Policy Case for OER  http://www.slideshare.net/iwmw/green-23500590
http://blog.edtechie.net/higher-ed/oer15-and-the-nature-of-change-in-higher-ed/
**** Writup https://catherinecronin.wordpress.com/2015/04/21/oer15/
**** more slides 
http://www.slideshare.net/search/slideshow?q=oersch15

**** Cracking Open Education May 2015 
http://blogs.sussex.ac.uk/tel/2015/05/12/cracking-open-education/

***** Finch Report 
http://www.researchinfonet.org/wp-content/uploads/2012/06/Finch-Group-report-FINAL-VERSION.pdf

*** Next step towards Open Education Open Education: From Open Practice to Open Policy 
    CETIS 2014
    https://lornamcampbell.files.wordpress.com/2014/06/cetis14_oer.pdf

**** open ed 2010
http://cloudworks.ac.uk/cloudscape/view/2083

OER the welsch experience :
http://www.slideshare.net/LornaMCampbell/oer-the-welsh-experience-by-paul-richardson
